"""Match each profile's model to THIS host's hardware, at setup time.

`config/models.yaml` pins a model per tier (fast/quality/synthesis/
quality_high) chosen against one specific machine — an RTX 2070 Super, 8 GB
VRAM, 24 GB RAM (ARCHITECTURE.md's "Hardware reality"). On a smaller box
`quality_high: qwen3:30b` is a 19 GB download that then thrashes; on a bigger
one the tracked choices leave capacity unused.

`llm.resolve_model` already adapts at RUN time, but only among models that are
already PULLED — which is too late to help the one step that decides what to
pull in the first place. This module runs before that step, so
`reel.manifest` → `scripts/update-models.sh` downloads the right set.

Two deliberate limits on how much this may do:

  * It only ever chooses from a profile's OWN declared candidates
    (`model` + `fallbacks`, in that preference order) — the curated ladder for
    that tier. It never invents a tag, so it can't pick a model nobody vetted
    for the tier's job.
  * It only writes an override when the tracked choice does NOT fit. On the
    machine models.yaml was tuned for, this is a no-op that writes nothing —
    the hand-tuned values stay authoritative, including the deliberate ones a
    naive size check would get wrong (`quality_high` prefers the 30b MoE over
    the same-size 32b dense model because it is ~6x faster, per that profile's
    own comment).

Overrides land in `config/models.local.yaml` (gitignored, deep-merged by
`llm.config`), never in the tracked file — see `llm.local_overrides`.

Scope is the `model` field only. `fallbacks` are deliberately left alone:
`llm.resolve_model` already filters them by fit at run time, so reordering
them here would duplicate that logic in a second place. `num_ctx` is likewise
untouched — it carries per-model VRAM reasoning (and `llm.local_max_chars`
derives the source-text budget from it), so it's a bigger decision than this
step should make silently.

Usage:
    python -m reel.hardware_config           # print the plan, change nothing
    python -m reel.hardware_config --apply   # write config/models.local.yaml
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import yaml

from . import llm

_HEADER = """\
# ─────────────────────────────────────────────────────────────────────────────
# Per-HOST model overrides — GENERATED by `python -m reel.hardware_config`
# (run automatically by `make setup`). Gitignored on purpose: config/models.yaml
# is tuned for one specific machine, and this file adapts it to yours.
#
# Deep-merged OVER config/models.yaml by llm.config(), field by field — an
# entry here overrides only the fields it names.
#
# Safe to hand-edit or delete: deleting it restores the tracked defaults, and
# re-running the command above rewrites only the `model` lines it manages.
# Detected at generation time: {hardware}
# ─────────────────────────────────────────────────────────────────────────────
"""


@dataclass
class Choice:
    """What this host should run for one profile, and why."""
    profile: str
    configured: str          # what config/models.yaml asks for
    chosen: str              # what actually fits here
    fits: bool               # whether `chosen` fits (False = nothing did)

    @property
    def changed(self) -> bool:
        return self.chosen != self.configured

    def describe(self) -> str:
        size = llm._model_size_mb(self.chosen)
        size_str = f"{size} MB" if size else "size unknown"
        if not self.fits:
            return (f"  {self.profile:<13} {self.chosen:<22} "
                    f"WARNING: no candidate fits this host — smallest ({size_str})")
        if not self.changed:
            return f"  {self.profile:<13} {self.chosen:<22} ok ({size_str})"
        return (f"  {self.profile:<13} {self.chosen:<22} "
                f"replaces {self.configured} ({size_str}, fits)")


def plan(
    cfg: dict | None = None,
    *,
    vram_mb: int | None = None,
    ram_mb: int | None = None,
) -> list[Choice]:
    """One `Choice` per LOCAL profile, in config order.

    Hosted profiles (`provider != "ollama"`) are skipped — their model runs on
    someone else's hardware, so local VRAM has no bearing on it, same reasoning
    as `manifest.models`.

    Judged against the TRACKED config (`llm.base_config`), never the merged
    one: an override already on disk must not become the baseline, or a host
    that grew — or one downgraded from a bad reading — could never be restored
    to the tracked model.
    """
    cfg = llm.base_config() if cfg is None else cfg
    if vram_mb is None:
        vram_mb = llm.gpu_vram_mb() or 0
    if ram_mb is None:
        ram_mb = llm.system_ram_mb()

    choices: list[Choice] = []
    for name in cfg.get("profiles", {}):
        try:
            p = llm.get_profile(name, cfg)
        except KeyError:  # pragma: no cover — same cfg drives both
            continue
        if p.provider != "ollama":
            continue
        candidates = [p.model, *p.fallbacks]
        fitting = [t for t in candidates
                   if llm.can_run_model(t, vram_mb=vram_mb, ram_mb=ram_mb)]
        if fitting:
            choices.append(Choice(name, p.model, fitting[0], fits=True))
        else:
            # Nothing fits: take the smallest candidate rather than leaving the
            # tier pointed at something guaranteed to OOM. Flagged, not silent.
            smallest = min(candidates, key=lambda t: llm._model_size_mb(t) or 0)
            choices.append(Choice(name, p.model, smallest, fits=False))
    return choices


def overrides(choices: list[Choice]) -> dict[str, str]:
    """profile name → model, for the profiles whose tracked choice doesn't fit."""
    return {c.profile: c.chosen for c in choices if c.changed}


def apply(
    choices: list[Choice],
    path: Path | None = None,
    *,
    hardware: str | None = None,
) -> dict[str, str]:
    """Write the overrides to the local overlay; return what was written.

    Rewrites ONLY the `profiles.<name>.model` keys this module manages — any
    other key a user hand-added to the overlay is carried through untouched,
    and a profile that now fits its tracked model has its stale override
    REMOVED (the hardware-upgrade case), rather than being pinned forever to
    whatever a smaller machine once needed.
    """
    path = llm.LOCAL_CONFIG_PATH if path is None else path
    wanted = overrides(choices)
    # `llm.config` caches both files for the process; this call just changed one.
    llm.config.cache_clear()

    existing = {}
    if path.exists():
        try:
            loaded = yaml.safe_load(path.read_text())
            existing = loaded if isinstance(loaded, dict) else {}
        except Exception:
            existing = {}

    profiles = dict(existing.get("profiles") or {})
    for c in choices:
        entry = dict(profiles.get(c.profile) or {})
        if c.profile in wanted:
            entry["model"] = wanted[c.profile]
        else:
            entry.pop("model", None)
        if entry:
            profiles[c.profile] = entry
        else:
            profiles.pop(c.profile, None)

    merged = dict(existing)
    if profiles:
        merged["profiles"] = profiles
    else:
        merged.pop("profiles", None)

    if not merged:
        # Nothing left to override — remove the file rather than leaving an
        # empty one that reads as "something was configured here".
        if path.exists():
            path.unlink()
        return wanted

    hardware = llm.hardware_summary() if hardware is None else hardware
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_HEADER.format(hardware=hardware)
                    + yaml.safe_dump(merged, sort_keys=False))
    return wanted


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--apply", action="store_true",
                    help=f"write the overrides to {llm.LOCAL_CONFIG_PATH.name} "
                         "(default: print the plan only)")
    args = ap.parse_args()

    hardware = llm.hardware_summary()
    choices = plan()
    print(f"Detected: {hardware}")
    print("Profile model fit (candidates come from each profile's own "
          "model + fallbacks):")
    for c in choices:
        print(c.describe())

    changed = overrides(choices)
    if not args.apply:
        if changed:
            print(f"\n{len(changed)} profile(s) would be overridden — "
                  "re-run with --apply to write "
                  f"{llm.LOCAL_CONFIG_PATH}")
        else:
            print("\nEvery profile's configured model fits — nothing to override.")
        return

    apply(choices, hardware=hardware)
    if changed:
        print(f"\nwrote {llm.LOCAL_CONFIG_PATH}:")
        for name, tag in changed.items():
            print(f"  {name}: {tag}")
        print("  (delete that file to restore the tracked defaults)")
    else:
        print("\nEvery profile's configured model fits — no overrides needed.")


if __name__ == "__main__":
    main()
